name: 'build example functions'
on:
  push:
    paths:
      - example/**
      - package/**
      - test-server/**

jobs:

  build-example-functions:
    name: 'Build example functions using CLI'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
        working-directory: package
      - name: Build package typescript
        run: pnpm run build
        working-directory: package
      - name: Build package for distribution
        run: pnpm run build:all
        working-directory: package
      - name: Build test-server typescript
        run: pnpm run build
        working-directory: test-server
      - name: Install package
        run: pnpm install
        working-directory: example
      - name: Build example functions
        run: pnpm run build >> $GITHUB_STEP_SUMMARY
        working-directory: example
      - name: Test with development server
        run: pnpm run test >> $GITHUB_STEP_SUMMARY
        working-directory: example
